### ISSUE TITLE
location_getCensusBlock()

### ISSUE THREAD

**Issue by jonathancallahan** [MazamaScience/MazamaLocationUtils#7] opened 2019-12-04 21:59 UTC
Create a `location_getCensusBlock()` function that obtains information from:

https://geo.fcc.gov/api/census/#!/block/get_block_find

Try it out by filling in latitude and longitude and requesting json output

We should consider the information here to be the gold standard for state and county -- _i.e._ this information could be used to override information we get elsewhere.

The piece of metadata we want to obtain is called `FIPS` in the json output and we should rename it to `censusBlock`. So this function will return a list with:

```
censusList <- list(
  stateCode = ...,
  county = ...,
  censusBlock = ...
)
```

Note that higher level census concepts like "block group" and "tract" are all just truncated versions of the `censusBlock` we obtain from this web site.

The point of getting and saving the census block is that it can be used to obtain _*tons*_ of other data -- basically anything in the census -- that might be useful to someone.

**Comment by oliverfogelin** [comment] 2019-12-07 22:53
Hi, sorry to bother you again! Is there any chance you could please mark this issue as closed? I just realised for the GCI competition I only get the credit once the issue is actually marked as done.

Thanks so much,
Oliver

**Closed** 2019-12-08 14:40 UTC
Labels: enhancement
